# Generated by Django 4.2 on 2024-07-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default=None)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'authors',
            },
        ),
    ]
